export const ROUTES = {
  START: '/',
  HOME: '/HomePage',
  LOGIN: '/LoginPage',
  SIGN_UP: '/SignUpPage',
  REGISTER: '/RegisterPage',
  FORGOT_PASSWORD: '/ForgotPasswordPage',
  PASSWORD_RESET: '/PasswordResetPage',
  CHANGE_PASSWORD: '/ChangePasswordPage',
  RENT: '/RentPage',
  MANAGE_CAR: '/ManageCarPage',
  EDIT_CAR: '/EditCarPage',
  ADD_CAR: '/AddCarPage',
  PROFILE: '/ProfilePage',
  SETTINGS: '/SettingsPage',
  ACCOUNT_SETTINGS: '/AccountSettingsPage',
  NOTIFICATIONS: '/NotificationsPage',
  NEWS_UPDATES: '/News&UpdatesPage',
  HELP: '/HelpPage',
  PAYMENT: '/PaymentPage',
  TERMS_OF_SERVICE: '/TermsOfService',
  PRIVACY_POLICY: '/PrivacyPolicy',
  EDIT_SPOT: '/EditSpotPage',
  MANAGE_SPOT: '/ManageSpotsPage',
  ADD_SPOT: '/AddSpotPage',
} as const;
