export const ROUTES = {
  START: '/',
  HOME: '/HomePage',
  LOGIN: '/LoginPage',
  SIGN_UP: '/SignUpPage',
  REGISTER: '/RegisterPage',
  FORGOT_PASSWORD: '/ForgotPasswordPage',
  PASSWORD_RESET: '/PasswordResetPage',
  RENT: '/RentPage',
  MANAGE_CAR: '/ManageCarPage',
  EDIT_CAR: '/EditCarPage',
  ADD_CAR: '/AddCarPage',
  PROFILE: '/ProfilePage',
  SETTINGS: '/SettingsPage',
  NOTIFICATIONS: '/NotificationsPage',
  NEWS_UPDATES: '/News&UpdatesPage',
  HELP: '/HelpPage',
  PAYMENT: '/PaymentPage',
  TERMS_OF_SERVICE: '/TermsOfService',
  PRIVACY_POLICY: '/PrivacyPolicy',
} as const;
